name: homeward_blog
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  #Used for responsive design for other devices than the phone
  responsive_builder: ^0.4.0-nullsafety.1
  http: ^0.13.1
  # Allows us to easily use custom fonts from Google Fonts.
  google_fonts: ^2.0.0
  #Used for state management
  provider: ^5.0.0
  cached_network_image: ^3.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
  - images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf


